### ISSUE TITLE
Имена полей http заголовка

### ISSUE THREAD

**Issue by nikelcase** [GyverLibs/GyverHTTP#1]
Согласно [RFC 7230 секция 3.2](https://www.rfc-editor.org/rfc/rfc7230#section-3.2) (обновление для [RFC 2616 секция 4.2](https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2)) имена полей не чувствительные к регистру

> Each header field consists of a case-insensitive field name followed by a colon (":"), optional leading whitespace, the field value, and optional trailing whitespace.

https://github.com/GyverLibs/GyverHTTP/blob/0bd48f0a55ccc9dd610527152b10ccbe6c87d177/src/utils/HeadersParser.h#L39
https://github.com/GyverLibs/GyverHTTP/blob/0bd48f0a55ccc9dd610527152b10ccbe6c87d177/src/utils/HeadersParser.h#L42
https://github.com/GyverLibs/GyverHTTP/blob/0bd48f0a55ccc9dd610527152b10ccbe6c87d177/src/utils/HeadersParser.h#L45

При этом методы (RFC 7230 секция 3.1.1) и версия протокола (RFC 7230 секция 2.6) чувствительны к регистру

И для примера можно посмотреть как производится парсинг в nginx https://github.com/nginx/nginx/blob/master/src/http/ngx_http_parse.c

**Comment by GyverLibs** [comment]
Да знаю, там ещё и пробелы лишние разрешены, но не встречал некрасивых ответов от сервера. Надо конечно lowercase добавить это да
