### ISSUE TITLE
StreamDev.h: No such file or directory

### ISSUE THREAD

**Issue by olehdutko** [GyverLibs/GyverHTTP#2]
the project that uses this lib failed.

Building in debug mode
Compiling .pio/build/d1_mini/src/main.cpp.o
Compiling .pio/build/d1_mini/lib967/ESP8266WiFi/ESP8266WiFiMulti.cpp.o
Compiling .pio/build/d1_mini/lib967/ESP8266WiFi/ESP8266WiFiSTA-WPS.cpp.o
Compiling .pio/build/d1_mini/lib967/ESP8266WiFi/ESP8266WiFiSTA.cpp.o
Compiling .pio/build/d1_mini/lib967/ESP8266WiFi/ESP8266WiFiScan.cpp.o
Compiling .pio/build/d1_mini/lib967/ESP8266WiFi/WiFiClient.cpp.o
Compiling .pio/build/d1_mini/lib967/ESP8266WiFi/WiFiClientSecureAxTLS.cpp.o
Compiling .pio/build/d1_mini/lib967/ESP8266WiFi/WiFiClientSecureBearSSL.cpp.o
In file included from .pio/libdeps/d1_mini/GyverHTTP/src/utils/ServerBase.h:8:0,
                 from .pio/libdeps/d1_mini/GyverHTTP/src/utils/Server.h:2,
                 from .pio/libdeps/d1_mini/GyverHTTP/src/GyverHTTP.h:6,
                 from src/Kandinsky/Kandinsky.h:13,
                 from src/gen.h:2,
                 from src/main.cpp:5:
.pio/libdeps/d1_mini/GyverHTTP/src/StreamWriter.h:5:23: fatal error: StreamDev.h: No such file or directory

**Comment by GyverLibs** [comment]
Maybe too old core version

**Comment by olehdutko** [comment]
Thanks for the quick answer! 
How can it be? the project was opened and all libs were installed

**Comment by GyverLibs** [comment]
core version is independent of project/libs, it's configurable in ur IDE

**Comment by olehdutko** [comment]
How can I config it in Arduino IDE/Platform IO (VScode)?

**Comment by GyverLibs** [comment]
use latest version, p.e. in PIO `platform = espressif8266`

**Comment by olehdutko** [comment]
PIO:
[env:esp_d1_mini]
platform = espressif8266
board = d1_mini
upload_speed = 921600
monitor_speed = 115200
monitor_filters = esp8266_exception_decoder, default
build_type = debug
board_build.filesystem = littlefs



ERROR:
Processing esp_d1_mini (platform: espressif8266; board: d1_mini; framework: arduino)
------------------------------------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/espressif8266/d1_mini.html
PLATFORM: Espressif 8266 (2.6.3) > WeMos D1 R2 and mini
HARDWARE: ESP8266 80MHz, 80KB RAM, 4MB Flash
PACKAGES: 
 - framework-arduinoespressif8266 @ 3.20704.0 (2.7.4) 
 - tool-esptool @ 1.413.0 (4.13) 
 - tool-esptoolpy @ 1.30000.201119 (3.0.0) 
 - toolchain-xtensa @ 2.40802.200502 (4.8.2)
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 43 compatible libraries
Scanning dependencies...
Dependency Graph
|-- AutoOTA @ 1.0.2
|-- Settings @ 1.0.24
|-- Adafruit ST7796S kbv @ 1.0.0+sha.ed568a3
|-- Adafruit GFX Library @ 1.11.10+sha.0e32d7d
|-- GyverDB @ 1.1.6
|-- LittleFS(esp8266) @ 0.1.0
|-- ESP8266WiFi @ 1.0
|-- GSON @ 1.5.9
|-- GyverHTTP @ 1.0.21
|-- StringUtils @ 1.4.26
Building in debug mode
Compiling .pio/build/esp_d1_mini/src/Kandinsky/tjpgd/tjpgd.c.o
Compiling .pio/build/esp_d1_mini/src/main.cpp.o
Generating LD script .pio/build/esp_d1_mini/ld/local.eagle.app.v6.common.ld
Compiling .pio/build/esp_d1_mini/lib967/ESP8266WiFi/BearSSLHelpers.cpp.o
Compiling .pio/build/esp_d1_mini/lib967/ESP8266WiFi/CertStoreBearSSL.cpp.o
Compiling .pio/build/esp_d1_mini/lib967/ESP8266WiFi/ESP8266WiFi.cpp.o
Compiling .pio/build/esp_d1_mini/lib967/ESP8266WiFi/ESP8266WiFiAP.cpp.o
Compiling .pio/build/esp_d1_mini/lib967/ESP8266WiFi/ESP8266WiFiGeneric.cpp.o
Compiling .pio/build/esp_d1_mini/lib967/ESP8266WiFi/ESP8266WiFiGratuitous.cpp.o
In file included from .pio/libdeps/esp_d1_mini/GyverHTTP/src/utils/ServerBase.h:8:0,
                 from .pio/libdeps/esp_d1_mini/GyverHTTP/src/utils/Server.h:2,
                 from .pio/libdeps/esp_d1_mini/GyverHTTP/src/GyverHTTP.h:6,
                 from src/Kandinsky/Kandinsky.h:13,
                 from src/gen.h:2,
                 from src/main.cpp:5:
.pio/libdeps/esp_d1_mini/GyverHTTP/src/StreamWriter.h:5:23: fatal error: StreamDev.h: No such file or directory

**Comment by GyverLibs** [comment]
![image](https://github.com/user-attachments/assets/b93767de-9ccf-44f7-81b1-917b43c0c091)

**Comment by olehdutko** [comment]
Can it be an issue on mac (M1) only?

**Comment by GyverLibs** [comment]
No. Maybe you should do `pio pkg update`

**Comment by olehdutko** [comment]
It solves my problem. Thank you! looks like `espressif8266@2.6.3` was cashed
Platform Manager: espressif8266@2.6.3 has been removed!
Platform Manager: Installing platformio/espressif8266 @ 4.2.1
Downloading  [####################################]  100%
Unpacking  [####################################]  100%
Platform Manager: espressif8266@4.2.1 has been installed!

**Comment by GyverLibs** [comment]
2.6.3 is so old yeah
